import bcrypt from 'bcryptjs';

const data = {
	users: [
		{
			name: 'Zakaria Admin',
			email: 'zsumonn@gmial.com',
			password: bcrypt.hashSync('Su112200', 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: 'Puma',
				logo: '/images/logo1.png',
				description: 'best seller',
				rating: 4.5,
				numReviews: 120,
			},
		},
		{
			name: 'Sumon',
			email: 'zaknetsum@gmail.com',
			password: bcrypt.hashSync('Su112200', 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: 'Lee',
				logo: '/images/logo2.png',
				description: 'best seller',
				rating: 4.5,
				numReviews: 120,
			},
		},
		{
			name: 'Sumon1',
			email: 'zaknetsum1@gmail.com',
			password: bcrypt.hashSync('Su112200', 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: 'Nike',
				logo: '/images/logo3.png',
				description: 'best seller',
				rating: 4.5,
				numReviews: 120,
			},
		},
		{
			name: 'Sumon2',
			email: 'zaknetsum2@gmail.com',
			password: bcrypt.hashSync('Su112200', 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: 'Adidas',
				logo: '/images/logo4.png',
				description: 'best seller',
				rating: 4.5,
				numReviews: 120,
			},
		},
	],
	products: [
		{
			name: 'Nike Slim Shirt',
			category: 'Shirts',
			image: '/images/p1.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Adidas Fit Shirt',
			category: 'Shirts',
			image: '/images/p2.jpg',
			price: 100,
			countInStock: 20,
			brand: 'Adidas',
			rating: 4.0,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Lacoste Free Shirt',
			category: 'Shirts',
			image: '/images/p3.jpg',
			price: 220,
			countInStock: 0,
			brand: 'Lacoste',
			rating: 4.8,
			numReviews: 17,
			description: 'high quality product',
		},

		{
			name: 'Puma Slim Pant',
			category: 'Pants',
			image: '/images/p5.jpg',
			price: 65,
			countInStock: 5,
			brand: 'Puma',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Adidas Fit Pant',
			category: 'Pants',
			image: '/images/p6.jpg',
			price: 139,
			countInStock: 12,
			brand: 'Adidas',
			rating: 4.5,
			numReviews: 15,
			description: 'high quality product',
		},
		{
			name: 'Nike Shirt',
			category: 'Shirts',
			image: '/images/p11.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Adidas Slim',
			category: 'Shirts',
			image: '/images/p8.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Adidas',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Adidas Fit Shirt',
			category: 'Shirts',
			image: '/images/p9.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Adidas',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
	],
};
export default data;
